[[session]]
  root = "$HOME/src/(*)"
  name = "src/$1"
  [[session.window]]
    name = "$1"
    kill = ["C-d"]

[logger]
  [logger.messages]
    level = "info"
    ttl = 5
  [logger.logfile]
    level = "debug"
    path = "$HOME/.cache/tiramisu/tiramisu.log"
