[logger]
  level = "trace"
  path = "log.log"

[messages]
  level = "trace"

[[session]]
  root = "$HOME/src/(*)"
  name = "src/$1"
  [[session.window]]
    name = "lalala"
    safe_kill = ["C-d"]

[[session]]
  root = "$HOME/tmp/(*)"
  name = "tmp/$1"
  [[session.window]]
    name = "lalala"
    safe_kill = ["C-d"]
